on:
    workflow_dispatch:
    repository_dispatch:
        types:
            - deploy

name: website

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  repository: wipplelang/wipple

            - run: |
                  rustup toolchain install stable --profile minimal
                  rustup target add wasm32-unknown-unknown

            - uses: peaceiris/actions-mdbook@v1
              with:
                  mdbook-version: "0.4.32"

            - uses: arduino/setup-task@v1
              with:
                  version: 3.x
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - run: task website
              env:
                  NODE_OPTIONS: --max-old-space-size=4096
                  SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
                  SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
                  SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
                  VITE_SENTRY_DSN: "${{ secrets.VITE_SENTRY_DSN }}"
                  VITE_P2P_SERVER: "${{ secrets.VITE_P2P_SERVER }}"
                  VITE_GA4_ID: "${{ secrets.VITE_GA4_ID }}"

            - uses: actions/upload-pages-artifact@v2
              with:
                  path: website/_site/

    deploy:
        needs: build

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
